### ISSUE TITLE
Support reactive streams

### ISSUE THREAD

**Issue by aurelijusb** [Auginte/scarango#1]
> Issue just for better development process: so I could mention issue number in commits and other could see near future plans

# Problem
Using `akka` actors is good for asynchronous operations, but it *too verbose* for developers.
Also using actor pattern, it becomes *hard to understand data flow*

# Solution
Use [akka streams](http://doc.akka.io/docs/akka/2.4.4/scala/stream/stream-quickstart.html) for abstraction over HTTP/Request and responses

# Expected result
I would like to have something like:
```scala
val new Scarango(context)
//...
Source.fromFuture[Documents](scarango.byExample("{a:{c:1}}"))
    .runForeach(println(_))
    .filter(raw => toProduct(raw).price < 5)
    .map(_.getId)
    .map(scarango.Remove)
```

- Getting results using `Source` notation
- Writing to database using `Flow` notation (so errors or success could be dealt with)

# Final goal

I could work with data flow like a stream:
- Store to database, while still receiving from stow connection
- Start responding to user, while not all elements are fetched from database (*is it possible from ArangoDB side?* - **not yet** - need stream based JSON parser)

# Tasks

- [x] GetVersion: infrastructure to get request using `reactive streams`
- [x] CreateDatabase: infrastructure to store to database
- [x] GetAllDocuments: to test responding to user, while still reading from database
- [x] StoreRawDocument: to test `back-pressure` from database to initial client
- [x] CRUD for Collections: to have self contained tests
- [x] CRUD for Database: to have fully functional tests (for test `_system` database could be used)
- [x] Other functional compatibility to meet `v0.2.4`
- [x] Solution/Tests for error handling
- [x] Documentation, code quality: readiness for end-usage
- [x] Prepare example documents

**Comment by aurelijusb** [comment]
API coverage, improvements and bug fixes will be in separate issue.
Functionality implemented and **released** under https://github.com/Auginte/scarango/releases/tag/v0.3.1
