### ISSUE TITLE
Support multiple ArangoDB versions

### ISSUE THREAD

**Issue by aurelijusb** [Auginte/scarango#2]
**Problem**
- Various companies use various ArangoDB versions.
- Need to support pre-release versions.
- Other developers create forks just to support newer versions: https://github.com/jaggernoth/scarango

**Tasks**

- [ ]  Update tests: to support overwriting ArangoDB version via environment variable
- [ ]  Update Travis integration: matrix builds
- [ ]  Compare test speed for ArangoDB as a dependencies via `docker` versus `TravisCI` build
